# Generated by Django 3.0.5 on 2020-04-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20200416_1927'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('challenge_online', models.IntegerField(blank=True, null=True)),
                ('challenge_onspot', models.IntegerField(blank=True, null=True)),
                ('cruiser_online', models.IntegerField(blank=True, null=True)),
                ('cruiser_onspot', models.IntegerField(blank=True, null=True)),
                ('junior_online', models.IntegerField(blank=True, null=True)),
                ('junior_onspot', models.IntegerField(blank=True, null=True)),
                ('elite_online', models.IntegerField(blank=True, null=True)),
                ('elite_onspot', models.IntegerField(blank=True, null=True)),
                ('mtb_online', models.IntegerField(blank=True, null=True)),
                ('mtb_onspot', models.IntegerField(blank=True, null=True)),
                ('other_online', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Club')),
            ],
        ),
    ]
