# Generated by Django 3.0.5 on 2020-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200418_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MCR', 'MCR'), ('CP', 'CP'), ('CL', 'CL'), ('ML', 'ML'), ('V', 'V')], max_length=10),
        ),
    ]
