# Generated by Django 3.0.5 on 2020-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200418_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
