# Generated by Django 3.0.5 on 2020-04-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventtype_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.EventType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='label',
            field=models.CharField(max_length=10),
        ),
    ]
