# Generated by Django 3.0.5 on 2020-04-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200418_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_code',
            new_name='event_type',
        ),
    ]
