# Generated by Django 3.0.5 on 2020-04-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200418_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_challenge',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_cruiser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_elite',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_junior',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_mtb',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_other',
        ),
    ]
