# Generated by Django 3.0.5 on 2020-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200418_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategories',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
