# Generated by Django 3.0.5 on 2020-04-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0019_eventcategories_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_id', models.IntegerField()),
                ('place', models.IntegerField()),
                ('points', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
