# Generated by Django 3.0.5 on 2020-04-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0016_rider_have_valid_licence'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingdata',
            name='uci_id',
        ),
        migrations.AddField(
            model_name='rankingdata',
            name='rider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riders.Rider'),
            preserve_default=False,
        ),
    ]
