# Generated by Django 3.0.5 on 2020-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bank_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='bank_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='swift',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
