# Generated by Django 3.0.5 on 2020-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20200416_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(choices=[('Praha', 'Praha'), ('Středočeský', 'Středočeský'), ('Západočeský', 'Západočeský'), ('Jihočeský', 'Jihočeský'), ('Ústecký', 'Ústecký'), ('Plzeňský', 'Plzeňský'), ('Karlovarský', 'Karlovarský'), ('Liberecký', 'Liberecký'), ('Parbubický', 'Parbubický'), ('Královéhradecký', 'Královéhradecký'), ('Vysočina', 'Vysočina'), ('Jihomoravský', 'Jihomoravský'), ('Moravskoslezský', 'Moravskoslezský'), ('Olomoucký', 'Olomoucký'), ('Zlínský', 'Zlínský')], max_length=255, null=True),
        ),
    ]
