# Generated by Django 3.0.5 on 2020-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200416_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='bank_account',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='bank_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='iban',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='swift',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
