# Generated by Django 3.0.5 on 2020-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20200416_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='bank_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='swift',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
