# Generated by Django 3.0.5 on 2020-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20200416_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='bank_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='company_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='swift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
