# Generated by Django 3.0.5 on 2020-04-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20200416_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
