# Generated by Django 3.0.5 on 2020-04-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0004_auto_20200416_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('uci_id', models.CharField(max_length=255)),
                ('plate', models.IntegerField()),
                ('transponder_20', models.CharField(max_length=10)),
                ('transponder_24', models.CharField(max_length=10)),
                ('transponder_mtb', models.CharField(max_length=10)),
                ('transponder_other', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('is_challenge', models.BooleanField(default=True)),
                ('is_elite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Club')),
            ],
        ),
    ]
