# Generated by Django 3.0.5 on 2020-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_cruiser',
            field=models.BooleanField(default=False),
        ),
    ]
