# Generated by Django 3.0.5 on 2020-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_rider_is_cruiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='path_to_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='transponder_20',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='transponder_24',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='transponder_mtb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='transponder_other',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
