# Generated by Django 3.0.5 on 2020-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_auto_20200416_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='uci_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
