# Generated by Django 3.0.5 on 2020-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_auto_20200416_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
