# Generated by Django 3.0.5 on 2020-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_rider_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='plate_2',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='plate',
            field=models.IntegerField(unique=True),
        ),
    ]
