# Generated by Django 3.0.5 on 2020-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0006_auto_20200416_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='plate_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
