# Generated by Django 3.0.5 on 2020-04-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0008_rider_is_approwed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='emergency_tel',
            new_name='emergency_phone',
        ),
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
