# Generated by Django 3.0.5 on 2020-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0009_auto_20200416_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='gender',
            field=models.CharField(choices=[('Man/Boys', 'Man/Boys'), ('Woman/Girls', 'Woman/Girls'), ('Other', 'Other')], default='M', max_length=50),
        ),
    ]
