# Generated by Django 3.0.5 on 2020-04-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0010_rider_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='gender',
            field=models.CharField(choices=[('Man/Boy', 'Man/Boy'), ('Woman/Girl', 'Woman/Girl'), ('Other', 'Other')], default='M', max_length=50),
        ),
    ]
