# Generated by Django 3.0.5 on 2020-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0012_auto_20200417_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
