# Generated by Django 3.0.5 on 2020-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0013_rider_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='plate',
            field=models.IntegerField(),
        ),
    ]
