# Generated by Django 3.0.5 on 2020-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0014_auto_20200418_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='gender',
            field=models.CharField(choices=[('Muž/Male', 'Muž/Male'), ('Žena/Female', 'Žena/Female'), ('Ostatní/Other', 'Ostatní/Other')], default='M', max_length=50),
        ),
    ]
