# Generated by Django 3.0.5 on 2020-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0015_auto_20200418_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='have_valid_licence',
            field=models.BooleanField(default=True),
        ),
    ]
